"""Offline sync service — idempotent ingestion of queued business events.

The client queues business actions (sale, purchase, ...) while offline.
Once back online, it POSTs a batch to `/inventory/offline-sync`. Each item
carries an `idempotency_key` (UUID v4 generated by the client) and the
server uses the unique constraint on `InventoryRecord.idempotency_key` to
guarantee that the same action is booked exactly once, even if the client
retries due to network flakiness.

Key properties:
- Pure core: `_build_inventory_record()` has no DB dependency and is easy to test.
- Race-safe: `IntegrityError` from concurrent inserts is caught and the
  duplicate is returned as `duplicate`, not an error.
- FK-safe: `product_id` is resolved/created from `product_name` when the
  client only knows a name (e.g. the POS "现金收款" cash sale).
"""

from __future__ import annotations

import logging
import uuid
from datetime import timedelta
from decimal import Decimal
from typing import TYPE_CHECKING

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError

from app.core.timezone import parse_iso_datetime, utc_now
from app.models.inventory import InventoryRecord
from app.services.batch import consume_batches_fifo_costed, create_batch
from app.services.sku_service import ensure_sku_for_category, resolve_sku_id


if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio import AsyncSession

    from app.schemas.inventory import OfflineSyncItem


logger = logging.getLogger(__name__)


# Default category for cash-register collections. The client can also use a
# real product_id / product_name for normal inventory events.
CASH_PRODUCT_NAME = "现金收款"


def _build_inventory_record(
    merchant_id: uuid.UUID,
    item: OfflineSyncItem,
    product_id: int,
    sku_id: uuid.UUID | None = None,
) -> InventoryRecord:
    """Build an InventoryRecord from a queued item without touching the DB."""
    if item.quantity is not None:
        qty = Decimal(str(item.quantity))
    elif item.total_amount is not None:
        # Fallback: for pure cash sales the amount is what matters; we record
        # quantity as a negative 1 "笔" bookkeeping unit that does not affect
        # physical stock, but still contributes to the ledger's total_amount.
        qty = Decimal("-1")
    else:
        qty = Decimal("0")

    # Resolve event_time; accept ISO strings or fall back to UTC now().
    event_time = utc_now()
    if item.event_time:
        parsed = parse_iso_datetime(item.event_time)
        if parsed is not None:
            event_time = parsed

    return InventoryRecord(
        merchant_id=merchant_id,
        product_id=product_id,
        sku_id=sku_id,
        quantity=qty,
        unit=item.unit or "斤",
        unit_cost=Decimal(str(item.unit_cost)) if item.unit_cost is not None else None,
        unit_price=Decimal(str(item.unit_price)) if item.unit_price is not None else None,
        total_amount=Decimal(str(item.total_amount)) if item.total_amount is not None else None,
        event_type=item.event_type,
        event_time=event_time,
        source=item.source or "offline",
        idempotency_key=item.idempotency_key,
        client_id=item.client_id,
        client_reference=item.client_reference,
        notes=item.notes,
    )


async def _resolve_product_id(
    db: AsyncSession,
    merchant_id: uuid.UUID,
    item: OfflineSyncItem,
) -> int:
    """Return a valid product_id for the item, creating a fallback if needed.

    Resolution order:
      1. If item.product_id is present, validate it belongs to the merchant.
      2. If item.product_name is present, look up by name under this merchant.
      3. If neither hits, create a default "现金收款" category for cash sales.
    """
    from app.models.product import ProductCategory

    if item.product_id is not None:
        product = await db.get(ProductCategory, item.product_id)
        if product:
            return product.id

    name = (item.product_name or CASH_PRODUCT_NAME).strip() or CASH_PRODUCT_NAME
    product = await db.scalar(select(ProductCategory).where(ProductCategory.name == name))
    if product:
        return product.id

    # Auto-create a fallback category so the foreign key is satisfied.
    # This is acceptable for the cash-register use case; normal inventory
    # events should send an explicit product_id.
    product = ProductCategory(
        name=name,
        unit="笔" if name == CASH_PRODUCT_NAME else (item.unit or "斤"),
        shelf_life_hours=24 if name == CASH_PRODUCT_NAME else 72,
        category_group="其他",
        is_active=True,
    )
    db.add(product)
    await db.flush()
    logger.info(
        "offline-sync auto-created product category: merchant=%s name=%s id=%s",
        merchant_id,
        name,
        product.id,
    )
    return product.id


async def upsert_offline_item(
    db: AsyncSession,
    merchant_id: uuid.UUID,
    item: OfflineSyncItem,
) -> dict:
    """Insert one offline item inside the caller-owned transaction.

    This function never commits or rolls back the outer transaction. Batch callers
    isolate each item with ``begin_nested()`` so one bad record cannot erase earlier
    successful records.
    """
    existing = await db.scalar(
        select(InventoryRecord).where(
            InventoryRecord.merchant_id == merchant_id,
            InventoryRecord.idempotency_key == item.idempotency_key,
        )
    )
    if existing:
        return {
            "idempotency_key": item.idempotency_key,
            "status": "duplicate",
            "record_id": str(existing.id),
            "message": "duplicate",
        }

    product_id = await _resolve_product_id(db, merchant_id, item)
    product_name = item.product_name if item.product_name else None
    sku_id = await resolve_sku_id(db, merchant_id, product_name=product_name, product_id=product_id)
    if sku_id is None:
        sku_id = await ensure_sku_for_category(db, merchant_id, product_id)
    record = _build_inventory_record(merchant_id, item, product_id, sku_id=sku_id)
    db.add(record)
    await db.flush()

    # Track batch lifecycle for inventory-aware events
    event_type = item.event_type
    product_name_str = item.product_name or f"商品{product_id}"
    now = utc_now()
    if event_type == "purchase":
        unit_cost = (
            Decimal(str(item.unit_cost)) if item.unit_cost is not None else None
        )
        await create_batch(
            db,
            merchant_id=merchant_id,
            product_id=product_id,
            product_name=product_name_str,
            batch_label=f"{product_name_str}-{now.strftime('%m%d%H%M%S')}",
            quantity=Decimal(str(abs(item.quantity))) if item.quantity else Decimal("0"),
            purchase_time=record.event_time,
            sku_id=sku_id,
            unit_cost=unit_cost,
        )
    elif event_type in ("sale", "waste"):
        qty = Decimal(str(abs(item.quantity))) if item.quantity else Decimal("0")
        if qty > 0:
            await consume_batches_fifo_costed(
                db,
                merchant_id,
                product_id,
                qty,
                sku_id=sku_id,
            )

    return {
        "idempotency_key": item.idempotency_key,
        "status": "created",
        "record_id": str(record.id),
        "message": "created",
    }


async def upsert_offline_items(
    db: AsyncSession,
    merchant_id: uuid.UUID,
    items: list[OfflineSyncItem],
) -> list[dict]:
    """Idempotently ingest a batch while isolating each item with a savepoint."""
    results: list[dict] = []
    for item in items:
        try:
            async with db.begin_nested():
                result = await upsert_offline_item(db, merchant_id, item)
        except IntegrityError as exc:
            # The savepoint has already rolled back. A concurrent request may have
            # inserted the same key, so re-check in the still-valid outer transaction.
            existing = await db.scalar(
                select(InventoryRecord).where(
                    InventoryRecord.merchant_id == merchant_id,
                    InventoryRecord.idempotency_key == item.idempotency_key,
                )
            )
            if existing:
                result = {
                    "idempotency_key": item.idempotency_key,
                    "status": "duplicate",
                    "record_id": str(existing.id),
                    "message": "duplicate",
                }
            else:
                logger.exception("offline-sync integrity error")
                result = {
                    "idempotency_key": item.idempotency_key,
                    "status": "error",
                    "record_id": None,
                    "message": f"integrity error: {exc}",
                }
        except Exception as exc:  # noqa: BLE001
            logger.exception("offline-sync item failed")
            result = {
                "idempotency_key": item.idempotency_key,
                "status": "error",
                "record_id": None,
                "message": str(exc),
            }
        # Create a dead-letter event for failed items, outside the savepoint
        if result["status"] == "error":
            await _log_dead_letter(db, merchant_id, item, result)
        results.append(result)
    return results


async def _log_dead_letter(
    db: AsyncSession,
    merchant_id: uuid.UUID,
    item: OfflineSyncItem,
    result: dict,
) -> None:
    """Persist a DeadLetterEvent for an item that failed to sync."""
    from app.models.dead_letter import DeadLetterEvent

    from sqlalchemy import select as _select

    # Check if a dead letter already exists for this idempotency key.
    if item.idempotency_key:
        existing_dl = await db.scalar(
            _select(DeadLetterEvent).where(
                DeadLetterEvent.merchant_id == merchant_id,
                DeadLetterEvent.idempotency_key == item.idempotency_key,
            )
        )
        if existing_dl:
            return

    dead_letter = DeadLetterEvent(
        merchant_id=merchant_id,
        idempotency_key=item.idempotency_key,
        event_type=item.event_type,
        payload=item.model_dump(),
        error_message=str(result.get("message", ""))[:1000],
        retry_count=0,
        max_retries=3,
        status="pending",
        next_retry_at=utc_now() + timedelta(minutes=5),
    )
    db.add(dead_letter)
