"""PostgreSQL Row-Level Security (RLS) — 多租户数据隔离的数据库层防线。

参考:
  - sqlalchemy-tenants: https://github.com/Telemaco019/sqlalchemy-tenants
  - Alasco Tech Blog: https://alasco.tech/2024/03/28/django-and-row-level-security/
  - PostgresConf 2024 RLS Deep Dive

设计原则:
  1. 应用层过滤 (Repository模式) + 数据库层强制 (RLS) = 双重保险
  2. 使用 contextvars 存储当前租户ID (线程+异步安全)
  3. 支持三种模式: 正常模式 | 绕过模式(管理员) | 禁用模式(迁移时)
"""

from __future__ import annotations

import contextvars
import logging

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession


logger = logging.getLogger(__name__)

# ── 租户上下文 (跨异步任务安全) ──────────────────────────────────────
tenant_ctx: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "current_tenant_id", default=None
)

# 特殊值
RLS_BYPASS = "__RLS_BYPASS__"  # 绕过所有 RLS (超级管理员)
RLS_NONE = "__RLS_NONE__"  # 未设置租户 → 所有查询返回空


# ── 表名列表 (所有需要租户隔离的表) ──────────────────────────────────
TENANT_SCOPED_TABLES: list[str] = [
    "inventory_records",
    "voice_logs",
    "recommendations",
    "ai_actions",
    "simulation_records",
    "batch_life_cycles",
    "merchant_preferences",
    "environment_records",
    "stocktake_sessions",
    "stocktake_items",
    "purchase_orders",
    "purchase_items",
    "expense_records",
    "food_safety_inspections",
    "food_safety_complaints",
    "pos_transactions",
    "pos_items",
    "media_assets",
    "feedback_items",
    "staff_members",
    "device_registrations",
    "reconciliation_records",
]


async def set_tenant_context(session: AsyncSession, tenant_id: str) -> None:
    """为当前数据库会话设置租户上下文。

    在每个请求开始时调用，确保后续所有查询自动过滤。
    """
    tenant_ctx.set(tenant_id)
    # PostgreSQL 会话变量 — RLS 策略读取此值
    await session.execute(text("SET app.current_tenant_id = :tid"), {"tid": tenant_id})


async def clear_tenant_context(session: AsyncSession) -> None:
    """清除租户上下文 (请求结束时调用)。"""
    tenant_ctx.set(RLS_NONE)
    await session.execute(text("RESET app.current_tenant_id"))


async def bypass_rls(session: AsyncSession) -> None:
    """临时绕过 RLS (仅供超级管理员操作使用)。

    Usage:
        async with bypass_rls_context(session):
            # 跨租户查询
            ...
    """
    tenant_ctx.set(RLS_BYPASS)
    await session.execute(text("SET app.current_tenant_id = :tid"), {"tid": RLS_BYPASS})


def get_current_tenant_id() -> str | None:
    """获取当前请求的租户ID (可在任何地方调用)。"""
    tid = tenant_ctx.get()
    if tid in (None, RLS_NONE, RLS_BYPASS):
        return None
    return tid


# ── RLS 策略 SQL (生成 Alembic migration 用) ─────────────────────────


def generate_rls_policy_sql(table_name: str) -> str:
    """为指定表生成 RLS 策略的 SQL。

    策略逻辑:
      - 如果 app.current_tenant_id = '__RLS_BYPASS__' → 允许所有行
      - 如果 app.current_tenant_id = '__RLS_NONE__' 或 NULL → 拒绝所有行
      - 否则 → 只返回 tenant_id 匹配的行
    """
    return f"""
-- Enable RLS on {table_name}
ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if any (for idempotent re-runs)
DROP POLICY IF EXISTS tenant_isolation_policy ON {table_name};

-- Create isolation policy
CREATE POLICY tenant_isolation_policy ON {table_name}
    FOR ALL
    USING (
        CASE
            WHEN current_setting('app.current_tenant_id', true) IS NULL
                THEN false
            WHEN current_setting('app.current_tenant_id') = '{RLS_NONE}'
                THEN false
            WHEN current_setting('app.current_tenant_id') = '{RLS_BYPASS}'
                THEN true
            ELSE merchant_id = current_setting('app.current_tenant_id')::uuid
        END
    )
    WITH CHECK (
        CASE
            WHEN current_setting('app.current_tenant_id', true) IS NULL
                THEN false
            WHEN current_setting('app.current_tenant_id') = '{RLS_NONE}'
                THEN false
            WHEN current_setting('app.current_tenant_id') = '{RLS_BYPASS}'
                THEN true
            ELSE merchant_id = current_setting('app.current_tenant_id')::uuid
        END
    );
"""


def generate_all_rls_sql() -> str:
    """生成所有表的 RLS 策略 SQL。"""
    statements = [
        "-- ============================================================",
        "-- PostgreSQL Row-Level Security for Multi-Tenant Isolation",
        "-- Generated by app.core.rls",
        "-- ============================================================",
        "",
    ]
    for table in TENANT_SCOPED_TABLES:
        statements.append(generate_rls_policy_sql(table))
    return "\n".join(statements)


def generate_rls_disable_sql() -> str:
    """生成禁用所有表 RLS 的 SQL (用于开发环境/迁移回滚)。"""
    statements = [
        "-- Disable RLS on all tenant-scoped tables",
    ]
    for table in TENANT_SCOPED_TABLES:
        statements.append(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
    return "\n".join(statements)
